# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='graphic',
            field=models.BooleanField(default=False),
        ),
    ]
